version: "3.7"

networks:
  intrasso4_network:
    name: ${PROJECT_NAME:-intrasso4}-dev_network
    driver: bridge

volumes:
  dbdatadir:
    name: ${PROJECT_NAME:-intrasso4}-dev_dbdatadir
  docdir:
    name: ${PROJECT_NAME:-intrasso4}-dev_docdir
  carteidentitedir:
    name: ${PROJECT_NAME:-intrasso4}-dev_carteidentitedir


services:

  web:
    image: nginx:1.19.7-alpine
    container_name: ${PROJECT_NAME:-intrasso4}-dev_webfront
    volumes:
       - ./app:/app
       - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - ${INTRASSO4_HTTP:-8080}:80
    networks:
      - intrasso4_network
    depends_on:
      - php

  php:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-intrasso4}-dev_php
    networks:
      - intrasso4_network
    volumes:
      - ./app:/app
      - docdir:/documentation
      - carteidentitedir:/carte-identite
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: ${PROJECT_NAME:-intrasso4bis}-dev_db
    restart: always
    command: ["postgres", "-c", "log_min_duration_statement=2000"]
    environment:
      POSTGRES_USER: ${INTRASSO4_DB_USER:-user}
      POSTGRES_PASSWORD: ${INTRASSO4_DB_PASSWORD:-pass}
      POSTGRES_DB: ${INTRASSO4_DB_NAME:-intrasso4}
    volumes:
      - dbdatadir:/var/lib/postgresql/data/
    networks:
      - intrasso4_network

  dbtest:
    image: postgres:13.2-alpine
    container_name: ${PROJECT_NAME:-intrasso4}-devtest_db
    restart: always
    environment:
      POSTGRES_USER: ${INTRASSO4_DB_USER:-user}
      POSTGRES_PASSWORD: ${INTRASSO4_DB_PASSWORD:-pass}
      POSTGRES_DB: ${INTRASSO4_DB_NAME:-intrasso4}
    networks:
      - intrasso4_network

  adminer:
    image: adminer
    container_name: ${PROJECT_NAME:-intrasso4}-dev_adminer
    restart: always
    ports:
      - 8089:8080
    networks:
      - intrasso4_network
    depends_on:
      - db
      - dbtest

  maildev:
    image: maildev/maildev
    container_name: ${PROJECT_NAME:-intrasso4}-dev_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - ${INTRASSO4_MAILDEV_HTTP:-8090}:80
    networks:
      - intrasso4_network
