# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    base_url: '%env(resolve:BASE_URL)%'
    dme_url: '%env(resolve:DME_URL)%'
    noreply_mail: '%env(NOREPLY_MAIL)%'
    noreply_mail_label: '%env(NOREPLY_MAIL_LABEL)%'
    carte_identite_directory: '%env(default:default_carte_identite_directory:CARTE_IDENTITE_DIRECTORY)%'
    default_carte_identite_directory: '/carte-identite'
    image_directory: '%env(default:default_image_directory:IMAGE_DIRECTORY)%'
    default_image_directory: '/app/public/assets/img/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    resto.image_uploader:
        class: RestoBundle\ImageUpload
        arguments: ['%images_directory%']

    App\Command\Cron\EmailRetardCommand:
        $noreply_mail: '%env(NOREPLY_MAIL)%'
        $noreply_mail_label: '%env(NOREPLY_MAIL_LABEL)%'